# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__rust_dmd", ...)

#' @docType package
#' @usage NULL
#' @useDynLib koopman.dmd, .registration = TRUE
NULL

# Core DMD
rust_dmd <- function(x, rank, center, dt, lifting, lifting_param) {
  .Call("wrap__rust_dmd", x, rank, center, dt, lifting, lifting_param)
}

rust_dmd_predict <- function(result_ptr, n_ahead, x0, method) {
  .Call("wrap__rust_dmd_predict", result_ptr, n_ahead, x0, method)
}

rust_dmd_reconstruct <- function(result_ptr, n_steps, modes_subset) {
  .Call("wrap__rust_dmd_reconstruct", result_ptr, n_steps, modes_subset)
}

rust_dmd_spectrum <- function(result_ptr, dt) {
  .Call("wrap__rust_dmd_spectrum", result_ptr, dt)
}

rust_dmd_stability <- function(result_ptr, tol) {
  .Call("wrap__rust_dmd_stability", result_ptr, tol)
}

rust_dmd_error <- function(result_ptr, x_ptr) {
  .Call("wrap__rust_dmd_error", result_ptr, x_ptr)
}

rust_dmd_dominant_modes <- function(result_ptr, n, criterion) {
  .Call("wrap__rust_dmd_dominant_modes", result_ptr, n, criterion)
}

rust_dmd_residual <- function(result_ptr, x_ptr) {
  .Call("wrap__rust_dmd_residual", result_ptr, x_ptr)
}

# Hankel-DMD
rust_hankel_dmd <- function(y, delays, rank, dt) {
  .Call("wrap__rust_hankel_dmd", y, delays, rank, dt)
}

rust_hankel_reconstruct <- function(result_ptr, n_steps) {
  .Call("wrap__rust_hankel_reconstruct", result_ptr, n_steps)
}

rust_hankel_predict <- function(result_ptr, n_ahead) {
  .Call("wrap__rust_hankel_predict", result_ptr, n_ahead)
}

# GLA
rust_gla <- function(y, eigenvalues_re, eigenvalues_im, n_eigenvalues, tol, max_iter) {
  .Call("wrap__rust_gla", y, eigenvalues_re, eigenvalues_im, n_eigenvalues, tol, max_iter)
}

rust_gla_predict <- function(result_ptr, n_ahead) {
  .Call("wrap__rust_gla_predict", result_ptr, n_ahead)
}

rust_gla_reconstruct <- function(result_ptr, modes_to_use) {
  .Call("wrap__rust_gla_reconstruct", result_ptr, modes_to_use)
}

# Maps
rust_generate_trajectory <- function(map_name, initial_condition, n_iter, params) {
  .Call("wrap__rust_generate_trajectory", map_name, initial_condition, n_iter, params)
}

# Harmonic
rust_harmonic_time_average <- function(map_name, initial_condition, observable, omega, n_iter, params) {
  .Call("wrap__rust_harmonic_time_average", map_name, initial_condition, observable, omega, n_iter, params)
}

rust_mesochronic_compute <- function(map_name, x_range, y_range, resolution, observable, omega, n_iter, params) {
  .Call("wrap__rust_mesochronic_compute", map_name, x_range, y_range, resolution, observable, omega, n_iter, params)
}

rust_classify_phase_space <- function(hta_magnitudes, resonating_threshold, chaotic_threshold) {
  .Call("wrap__rust_classify_phase_space", hta_magnitudes, resonating_threshold, chaotic_threshold)
}

rust_hta_convergence <- function(map_name, initial_condition, observable, omega, n_iter, params) {
  .Call("wrap__rust_hta_convergence", map_name, initial_condition, observable, omega, n_iter, params)
}
